### PR TITLE
Add Github PR resource

### PR DESCRIPTION
**Pull request by itsdalmo**
This PR adds the `github-pr-resource` resource type to the list.

### CODE REVIEW

**Review by YoussB — APPROVED** [review]
LGTM 🥇

**Comment by itsdalmo** [comment]
Someone with write access needs to merge 😅

**Comment by YoussB** [comment]
Well, I could swear I merged it, but Github disagrees 😁 
https://github.com/concourse/resource-types/commit/81c35d8e928df800048565a446bcfb3b12bc56b1

**Comment by YoussB** [comment]
The commit has already made it to the live website https://resource-types.concourse-ci.org
looks like Github is having some problems, will just close the PR.

**Pull request closed without merging**
