### PR TITLE
Add makohoek/repo-resource

### PR DESCRIPTION
**Pull request by makohoek**
Track changes for projects using (Google's) repo.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>

### CODE REVIEW

**Comment by makohoek** [comment]
@xtremerui any feedback on this?

Thank you for your time

**Comment by xtremerui** [comment]
Hi, sorry for the delay. I didn't receive the notification so thx for pinning me.

I checked the code base and notice there is no doc about `check` `in` and `out` like most other concourse resources. It is not our concern just to make sure.

**Comment by makohoek** [comment]
No worries. Thank you for having a look. I confirm that there is no specific configuration for `check`, `in` and `out`. Everything is configured via the resource definition.

I will add additional `check`, `in` and `out` sections to match `git-resource` (https://github.com/concourse/git-resource)
Mainly to describe the resource's behaviour.

Thank you for bringing that up.
Will ping you here once the README in `makohoek/repo-resource` is updated.

**Comment by makohoek** [comment]
@xtremerui I've update the README via https://github.com/makohoek/repo-resource/pull/24

Thanks again for your feedback :+1:

**Review by xtremerui — APPROVED** [review]
LGTM!

**Pull request merged**
