### PR TITLE
add flavorjones/webhook-notification-resource

### PR DESCRIPTION
**Pull request by flavorjones**
Signed-off-by: Mike Dalessio <mike.dalessio@gmail.com>

### CODE REVIEW

**Comment by flavorjones** [comment]
Related: https://github.com/flavorjones/webhook-notification-resource/issues/2

**Review by jomsie — APPROVED** [review]
thank you for your submission mr jones, looks good!

**Comment by flavorjones** [comment]
thumbs-up-simon-pegg

**Comment by jomsie** [comment]
bear

**Pull request merged**
