### PR TITLE
Add sentry releases resource

### PR DESCRIPTION
**Pull request by rubenv**
Signed-off-by: Ruben Vermeersch <ruben@rocketeer.be>

### CODE REVIEW

**Review by YoussB — APPROVED** [review]
Thanks @rubenv, I will just remove the `-resource` from the name in the yml file

**Comment by YoussB** [comment]
merged 52c376270b96e77b500bab0fab5996904b76d34f

**Comment by rubenv** [comment]
Thanks!

I wasn't sure about what the convention was: the official resources have (or had) that suffix, whereas the other PRs didn't.

**Comment by YoussB** [comment]
yup, that was absolutely my fault! I forgot to remove the `-resource` from the original ones!

**Pull request closed without merging**
