### PR TITLE
Add New Relic deployment marker resource

### PR DESCRIPTION
**Pull request by shyamz-22**
Signed-off-by: Syamala Umamaheswaran <shykart2203@gmail.com>

### CODE REVIEW

**Review by jomsie — CHANGES_REQUESTED** [review]
Hi!

Just wondering if you could add the `.yml` extension on the `shyamz-22-newrelic-deployment-resource` file?

Thanks!

**Comment by shyamz-22** [comment]
@jomsie Sorry, I have added it now

**Review by jomsie — APPROVED** [review]
looks good! thanks for the addition! :)

**Comment by jomsie** [comment]
the website just got updated, thanks again!

**Pull request merged**
