### PR TITLE
Adding vRealize Automation Resource Type

### PR DESCRIPTION
**Pull request by vishweshwarp**
Signed-off-by: Vishweshwar Palleboina <vishu0207@gmail.com>

### CODE REVIEW

**Review by taylorsilva — CHANGES_REQUESTED** [review]
Thanks for the PR!

Sadly the `projects.registry.vmware.com` isn't public. Only people inside the vmware network will be to access this image 😞 
Is it possible for you to host the image somewhere publicly as well?

**Comment by vishweshwarp** [comment]
@taylorsilva Thanks for looking into this PR.

`projects.registry.vmware.com` is an open registry hosted by VMware for sharing images with the community. Everyone can pull public images from here but the push is allowed by only VMware.

You can try pulling this resource type image and it should work as it is public and open to all: 
`docker pull projects.registry.vmware.com/concourse-vra-resource/concourse-vra-resource`

**Review by taylorsilva — APPROVED** [review]
I totally can pull the image when I'm not on the network! Weird that the harbor front-end doesn't load though. Would be nice if that part was public as well, not just the image pulling. I figure that's out of your hands though so I'll approve this :)

**Comment by taylorsilva** [comment]
Actually looks like I don't have merging rights! 😱 
@YoussB @jomsie @vito 
Can one of y'all merge and then see if you can grant the entire team access to manage the repo? Thanks!

**Comment by jomsie** [comment]
> Actually looks like I don't have merging rights! 😱
> @YoussB @jomsie @vito
> Can one of y'all merge and then see if you can grant the entire team access to manage the repo? Thanks!

I don't think I have merging rights anymore either! 😢

**Comment by vito** [comment]
@taylorsilva fixed!

**Comment by vishweshwarp** [comment]
When do we see this resource type live on https://resource-types.concourse-ci.org/ page? Any additional actions need to be performed for that?

**Comment by taylorsilva** [comment]
Looks like the pipeline that deploys the site is broken. We'll have to fix it before the site updates is my guess.

**Comment by taylorsilva** [comment]
It's up now!

**Pull request merged**
